programma: queue_con_stack.o stack.o stack.h
	gcc queue_con_stack.o stack.o -o programma

queue_con_stack.o: queue_con_stack.c stack.h
	gcc -c queue_con_stack.c 

stack.o: stack.c stack.h
	gcc -c stack.c 